### ISSUE TITLE
Middleware isn't refreshing expired token on page load

### ISSUE THREAD

**Issue by mayteio** [awinogrodzki/next-firebase-auth-edge#103]
Hey there! Thanks for the great lib. We're struggling to understand a token expiry/refresh token edge case where we use the token in a server component to fetch some data, i.e.

1. User gets a token, loads data from our back-end as expected
2. User closes the app
3. One hour+ later, the user re-opens the same page, token is expired
4. Request made to next.js server
5. Request made to our back-end server with expired token, fails
6. Nothing returned to user because token was expired

I would expect that middleware sits in between #4 and #5, refreshing the token when it's expired, then continuing with the server-component's request.

For reference, here's how we're making the request in the server component using `urql`:

```tsx
export default async function Dashboard() {
  // urql client
  const client = useServerGQLClient();

  const result = await client.query(GetPartnerProjects, {});

  return <MyProjects projects={result.data.projects} />
}
```

The [`urql`](https://github.com/urql-graphql/urql) client grabs the latest token from cookies on every request:

```ts
  addAuthToOperation(operation) {
      const _cookies = cookies();
      const tokens = _cookies.get("id-token")?.value; // the next-firebase-auth-edge id/refresh token
      if (!tokens) return operation;
      const { idToken } = JSON.parse(atob(tokens));
      return utils.appendHeaders(operation, {
        Authorization: `Bearer ${idToken}`,
      });
    }
```

I realise the use of `urql` muddies the water a bit, but just wondering:
1. If we're doing this right, or if we need to detect token expiry ourselves and use `refreshAuthCookies` manually
2. If there's anything we can do to rule out that this lib is working as expected and it's a `urql` issue

Thanks so much!

**Comment by awinogrodzki** [comment]
Hey @mayteio! Thank you for reporting the issue. 

There is a window for inconsistency within your code. The middleware is actually refreshing the token (you can notice it by inspecting `Set-Cookie` header returned from Next.js server after an hour. 

The issue here is this:

```tsx
  addAuthToOperation(operation) {
      const _cookies = cookies();
      const tokens = _cookies.get("id-token")?.value; // the next-firebase-auth-edge id/refresh token
      if (!tokens) return operation;
      const { idToken } = JSON.parse(atob(tokens));
      return utils.appendHeaders(operation, {
        Authorization: `Bearer ${idToken}`,
      });
    }
```

The call you make here has non-zero chance of failing once in an hour. 

The reason is: `Middleware` is rewriting only response headers. It does not change current request cookie headers.

Does `addAuthToOperation` have to be synchronous?

You could do something like this:
```tsx
async addAuthToOperation(operation) {
      const _cookies = cookies();
      const tokens = await getTokens(_cookies, AUTH_OPTIONS); 
      if (!tokens) return operation;
     
      return utils.appendHeaders(operation, {
        Authorization: `Bearer ${tokens.idToken}`,
      });
    }
```

But... I think I can make middleware rewrite request cookies as well. That way this function could stay synchronous. 

I can prepare a pre-release version with that for you to test today.

**Comment by awinogrodzki** [comment]
@mayteio, I have prepared a pre-release version of next `next-firebase-auth-edge` with **token verification caching**.

It should solve your problem.

You can test it by installing `next-firebase-auth-edge@0.9.0-1`

Please follow [Middleware token verification caching](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/3226f3bcc3fac0c91f42c2e9cd57b760d1e092df/README.md#middleware-token-verification-caching) section in upcoming README to enable it.

Let me know if that works!

**Comment by mayteio** [comment]
@awinogrodzki thanks so much for the prompt response! Yep, later figured out that middleware just sends the `Set-Cookie` header which isn't actually set until the `NextResponse` hits the browser. I will check this out today and report back 🙏🏻 cc @spatial-andrewc

**Comment by spatial-andrewc** [comment]
Hi @awinogrodzki. We were originally trying to set the cookie by looking at the `Set-Cookie` header in our `addAuthToOperation` fn and taking the value from there instead of request cookies if it existed to ensure we had the valid token at all times. We found this to work locally, but it was inconsistent on deployed versions of our app.

I then installed `next-firebase-auth-edge@0.9.0-1` and added the headers onto the request headers that entered the `authentication` fn in middleware. We're using `next-intl/middleware` here so I've added the headers like so:

`const i18nMiddleware = createMiddleware({ locales, defaultLocale })`

```
handleValidToken: async (_, headers) => {
    for (const [key, value] of Object.entries(headers)) {
        request.headers.set(key, value);
    }
}

return i18nMiddleware(request)
```

It seems to have fixed the issue and we're no longer sending expired tokens to our backend API service in `addAuthToOperation`. Have we gone about this the right way?

**Comment by awinogrodzki** [comment]
@spatial-andrewc I think you can try removing 
```tsx
 for (const [key, value] of Object.entries(headers)) {
      request.headers.set(key, value);
  }
```

`next-intl` already passes request.headers as `NextResponse.next({  request: { headers: request.headers } })` and by the time `createMiddleware` is called, request is already decorated with modified headers.

That's what I experience anyway. Could you test it?

**Comment by spatial-andrewc** [comment]
@awinogrodzki - yes, you're right. Thank you!
