### ISSUE TITLE
Suggestions to improve the architecture of the library

### ISSUE THREAD

**Issue by websiddu** [awinogrodzki/next-firebase-auth-edge#116]
Hello,

Firstly, I'd like to express my gratitude for creating such an invaluable library. I've been exploring its functionalities and have some suggestions that could be considered for its upcoming versions. I'm more than willing to contribute if these resonate with your vision.

**Motivation:**
For real-world applications, there's often a need to perform additional operations during login and logout processes, such as manipulating cookies. The presence of an extensive configuration object in the middleware can be intimidating for new users. Simplifying this aspect can make the initial experience with the library more user-friendly.

**Proposed Enhancements:**

1. **Modular Design:** Separate the Next.js components from the authentication segments. Consider omitting the Next.js components entirely, instead providing them within the "Getting Started" documentation.
2. **Enhanced Authentication Features:** Elevate the authentication functionality. For instance, integrating features like signInWithCredential and sendSignInLinkToEmail would be beneficial. Proper documentation around these would be vital.
3. **Custom API Routes:** Encourage users to define their API routes, such as /api/login/route.ts and /api/logout/route.ts, along with middleware.ts. We can provide templates or snippets for them to easily copy and integrate. As an analogy, the approach in "shadcn ui" is a prevalent one. Perhaps, we could even introduce a command like nxp create fb-edge-auth to streamline this.
4. **Expand Utility Functions:** Introduce more utility functions akin to getServerSession from next-auth.
5. **Development Mode:** Incorporate a debug mode exclusive for development. This can assist developers in quickly identifying and rectifying issues.

I look forward to your thoughts on these suggestions. Thanks for your time and commitment to the community.

**Comment by awinogrodzki** [comment]
Hey @websiddu,

That sounds amazing! Here is my comment:

> Modular Design: Separate the Next.js components from the authentication segments. Consider omitting the Next.js components entirely, instead providing them within the "Getting Started" documentation.

 I am not sure I follow here. You say README should mention only the middleware function itself, and other stuff, such as AuthProvider example should be moved to Getting Started guide?
 

>  Enhanced Authentication Features: Elevate the authentication functionality. For instance, integrating features like signInWithCredential and sendSignInLinkToEmail would be beneficial. Proper documentation around these would be vital

Definitely. Adding new methods based on `firebase-admin` is relatively easy. We could streamline this by creating a list of tasks in  Github Projects


> Custom API Routes: Encourage users to define their API routes, such as /api/login/route.ts and /api/logout/route.ts, along with middleware.ts. We can provide templates or snippets for them to easily copy and integrate. As an analogy, the approach in "shadcn ui" is a prevalent one. Perhaps, we could even introduce a command like nxp create fb-edge-auth to streamline this.

Personally, I didn't like the idea of using dedicated /login and /logout API Routes. I am working on 4-5 projects that use `next-firebase-auth-edge` and having to keep up-to-date routes would be painful, but I understand that some people would actually benefit this.

Probably we can make custom API routes optional to give more flexibility to users on how they use the endpoints.

> Expand Utility Functions: Introduce more utility functions akin to getServerSession from next-auth.

Could you provide some example use case here? There is no concept of `session` in `next-firebase-auth-edge`. The session is actually the token itself.

> Development Mode: Incorporate a debug mode exclusive for development. This can assist developers in quickly identifying and rectifying issues.

I would most definitely use it!


Thanks for taking the time and great ideas to improve the library.

I feel like `1.0` release is pretty close, and I could celebrate it with some dedicated docs website, akin to https://next-intl-docs.vercel.app/

Also, I was thinking about introducing more ways to define credentials rather than passing service account to every function. 
When fixing https://github.com/awinogrodzki/next-firebase-auth-edge/issues/109 I would explore ways how Firebase Admin shares credential across the app. It will be a good start to remove the need of passing service account credentials everywhere.

To me, it looks like I should start working on a project backlog.

I invited you to Github Project: https://github.com/awinogrodzki/next-firebase-auth-edge/projects?query=is%3Aopen

I will soon start preparing a list of issues to get us to v1 with some shiny looks :-)

**Comment by awinogrodzki** [comment]
Hey @websiddu!

I just released `next-firebase-auth-edge@1.0.0` with new, dedicated documentation page:

https://next-firebase-auth-edge-docs.vercel.app/

Please let me know if you have any other suggestions :-)
