### ISSUE TITLE
Token seams to be considered valid even after I delete the user from Firebase.

### ISSUE THREAD

**Issue by rgbskills** [awinogrodzki/next-firebase-auth-edge#136]
I have a navigation bar that displays the user's avatar when they are logged in. If the user is not logged in, it shows a login/register button instead. However, I encountered an issue: after deleting a user, the avatar no longer appears as expected, but when I click on the login button, it still redirects me to the homepage ("/") instead of allowing me to log in again, even though the user has been deleted.

**Comment by awinogrodzki** [comment]
Hey @rgbskills! 

That's pretty common problem. `next-firebase-auth-edge` does not validate token against Google server unless it's expired or you pass `checkRevoked: true` option to `authentication` middleware. 

After you delete the user, the token will stay valid until next refresh. 

To solve this problem, you can follow two approaches:

1. Backend-side solution: Set `checkRevoked: true` option in `authentication` middleware for users that have been deleted (I would not recommend setting this for every user, since it would mean calling Google APIs on each request), but it would not be trivial nor lightweight solution.

2. Client-side solution: `onIdTokenChanged` Firebase Authentication handler would be called with `null` if user was not found. That is why you don't see user's avatar when you refresh the page.

Whenever `onIdTokenChanged` returns null, but `getTokens()` returns valid `decodedToken`, you can call `/api/logout` to clear user cookies immediately. This should be pretty robust solution – after cookies are cleared, clicking on login button should no longer redirect user to the home page. If it does, make sure to set `preload={false}` on `next/link` component.

Personally, I would go with `2.`. Let me know if it helps!

**Comment by rgbskills** [comment]
Can you give me an example with solution 2 ?

**Comment by awinogrodzki** [comment]
Based on the starter example [AuthProvider](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/auth/client-auth-provider.tsx#L32-L41)

You can make it as follows:

```tsx
  const handleIdTokenChanged = async (firebaseUser: FirebaseUser | null) => {
    if (!firebaseUser) {
      await fetch('/api/logout'); // <!---  This line
      setUser(null);
      return;
    }

    const idTokenResult = await firebaseUser.getIdTokenResult();

    setUser(toUser(firebaseUser, idTokenResult));
  };
```

**Comment by awinogrodzki** [comment]
You can now follow resolution from https://github.com/awinogrodzki/next-firebase-auth-edge/issues/137#issuecomment-1893999193 to fix client/server inconsistency issue
