### ISSUE TITLE
Update request headers on declared response

### ISSUE THREAD

**Issue by zenicek** [awinogrodzki/next-firebase-auth-edge#140]
Hello,

I have updated my Next project dependencies and now I am getting the warning from the middleware.

`next-firebase-auth-edge: NextResponse returned by handleValidToken was not decorated by modified request headers. This can cause token verification to happen multiple times in a single request. See: https://github.com/awinogrodzki/next-firebase-auth-edge#middleware-token-verification-caching`

The problem is that in docs your response looks like this which create a brand new response with modified headers:

```
return NextResponse.next({
        request: {
          headers,
        },
      });

```

However, I declare the response at the top of my middleware and it goes through a couple of stages in the middleware where it is being modified for example by `edge-csrf` library for security.

So my response looks like the following:

```
export async function middleware(request: NextRequest) {
  const response = NextResponse.next();

  const csrfError = await csrfProtect(request, response);

  if (csrfError) {
      return new NextResponse('Unauthorized', { status: 403 });
    
  }
  return authentication(request, {...};
```

I have found similar question asked [here](https://stackoverflow.com/questions/75493460/returning-nextresponse-with-modified-responses-and-modified-nextrequest), and I think there is no way to update headers on existing response, also I did not find a way to maybe combine the two together.

I think the link in the warning is also out of date.

**Comment by zenicek** [comment]
Hi @awinogrodzki,

Sorry, I should have mentioned that changing the execution order helped. Although thinking purely from the logical perspective, it may make sense to check that the request is valid first (e.g., the csrf token is valid, etc..) before passing it to the auth and other middlewares. At least if the request is invalid, you can throw an error early and reduce the number of requests and execution instead of checking the token at the end, which is quite a cheap operation.

Thanks for updating the link and pointing out the authentication, I have updated it to `authMiddelware` 👍

**Comment by awinogrodzki** [comment]
I totally understand your point. I will be rethinking this modified headers approach to allow better flexibility in situations like this.

**Comment by awinogrodzki** [comment]
Hey, I spent some time investigating if I could change the behaviour in order to allow authMiddleware to be called before `csrfProtect`. Unfortunately, current implementation of Next.js limits us by requirement to pass [Modified Request Headers](https://vercel.com/templates/next.js/edge-functions-modify-request-header) as an argument to `NextResponse.next`.

There is no other way to modify request headers on existing response. Due to this fact, `authMiddleware` has to be called at the top level.

I will close the issue for now. If Next.js upgrades its API and allows to modify request headers on existing response instance, I will reopen the issue.

Cheers 🎉
