### ISSUE TITLE
`providerId ` is always set to `custom` making it impossible to distinguish between cases of when a verification email needs to be sent

### ISSUE THREAD

**Issue by MartinXPN** [awinogrodzki/next-firebase-auth-edge#147]
I'm trying to send verification emails for users that have signed in with email/password.
Yet, I've noticed that the `providerData.providerId` is always set to `custom` when using `next-firebase-auth-edge`.
When trying to use `Facebook` or `Microsoft` login, the `emailVerified` field is always set to `false` - but we don't know if it's `Facebook` or `Microsoft` as the `providerData.providerId=custom`. 
I was wondering if there is any way of making this work. 

The current behavior:
It's first set to the correct sign-in provider but then switches to `custom`.
Seems like the `providerData.providerId` is always set to `custom` when loading from `cookies()`.

**Comment by awinogrodzki** [comment]
Hey @MartinXPN! Thanks for reporting the issue. 

The reason is quite simple – the `idToken` received from client is exchanged on the backend for [custom token](https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithCustomToken) that has different properties than the initial token.

`emailVerified=false` is a bug and should definitely not happen in case of external providers. I will look into possible ways to fix that. 

`providerData.providerId=custom` is expected, but we're loosing some key information about the provider, which can be troublesome in number of cases. It might be that we can override this value with what's in original token. I'll keep you updated on that.

**Comment by MartinXPN** [comment]
Thanks! Would be great to have either of those working. I'm currently setting the provider id on the client side (onTokenChange) as a temporary workaround.

**Comment by awinogrodzki** [comment]
Hey @MartinXPN!

In `next-firebase-auth-edge@1.3.0-canary.6` I've released following improvements:

1. `DecodedIdToken` now has `email_verified` claim based on the original token. This should solve the issue your having with `emailVerified: false`

2. `DecodedIdToken` has been updated with `source_sign_in_provider` claim that contains original token's provider ID.
Firebase does not allow us to overwrite default `firebase.sign_in_provider` claim (that corresponds to `providerId`)  when creating a custom token. `source_sign_in_provider` should solve the problem you're having with `providerId`.

Please test it and let me know if it works for you! 

🍻

**Comment by MartinXPN** [comment]
Seems to be working fine. Thanks!
