### ISSUE TITLE
How to securely fetch Firestore data that is not keyed by user ID in a server component?

### ISSUE THREAD

**Issue by optimistiks** [awinogrodzki/next-firebase-auth-edge#157]
In the example, it shows how to fetch a counter record in a React Server Component

https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/examples/next13-typescript-starter/app/profile/page.tsx#L22

It works because user ID originates from a secure cookie. 

However, imagine we have another entity, let's say, `Story`. One user can have multiple stories. A user must only have access to their own stories (this is enforced via Firestore security rules). 

In the app router we have a `story/[storyId]` page. We navigate to `myapp.com/story/123`, we grab `storyId` from the route params. And we do this

```
const snapshot = await db
    .collection('user-stories')
    .doc(storyId)
    .get();
```

The problem with this is that it bypasses all the security rules, and I can use a story ID of a different user in the url and it will fetch it anyway. 

One solution is to manually check the resulting `story.userId` against `tokens.decodedToken.uid` and throw an exception in case of a mismatch. What this essentially means is that you have to recreate all your security rules in your server component code and then keep them in sync. 

Another solution is to use client SDK on the server and authenticate it using `signInWithCustomToken`, and fetch data with it. It will respect all the security rules. However, it seems like it will not work since the authentication state of the client SDK persists in memory (https://github.com/firebase/firebase-admin-node/issues/1141#issuecomment-1126815620) meaning two requests from different users will conflict with each other potentially changing the state of the sdk that is currently being used in a different request. 

Is there any other solution out there that I might have missed?

**Comment by awinogrodzki** [comment]
Hey @optimistiks,

Great question.

Security rules are compatible only with the client SDKs, see: https://stackoverflow.com/questions/69133455/firebase-firestore-security-rules-for-backend-service

`firebase-admin` and `next-firebase-auth-edge` both bypass all the security rules and allow full access to Firebase services, thus require you to implement a separate access validation mechanism

Firebase has a guide on how to approach backend access validation using **custom claims**
https://firebase.google.com/docs/auth/admin/custom-claims

The library allows you to fully manipule custom claims, as you would with `firebase-admin` library. There are also usage examples on refreshing user credentials after updating custom claims:
https://next-firebase-auth-edge-docs.vercel.app/docs/usage/refresh-auth-cookies

My personal opinion is that, in order to reduce complexity, you should migrate to one solution or the other. Given that you're planning on using backend authentication, it's worth to consider migrating security rules to the backend as well. One up side of such migration would be a reduction of client bundle size, which will definitely benefit users. I realise that this is not possible in every case. In case of bigger migration, I would keep two types of access validation, with the intention to migrate fully to one of them.

**Comment by awinogrodzki** [comment]
Closing the issue
