### ISSUE TITLE
We should ensure Google APIs keys are not cached by vercel

### ISSUE THREAD

**Issue by asaroukou** [awinogrodzki/next-firebase-auth-edge#159]
Hello,

First of all, thank you for the amazing work done in this library.
We are experiencing token validation issues with our project.
After investigation, it turn out our hosting service (Vercel) was caching the fetch result for the google keys here https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com leading to `NO_MATCHING_KID` error.

what we tried and that works so far to overcome this issue is adding `{cache: "no-store"}` to the fetch request.
```typescript
private async fetchPublicKeysResponse(url: URL): Promise<PublicKeysResponse> {
    const res = await fetch(url, {
        cache: "no-store",
    });
...
}
```

While we are still using the `v0.9.5` we are able to confirm that the issue still exists in the last version to date.

Thank you again.

**Comment by awinogrodzki** [comment]
Hey @asaroukou! 

Thank you for reporting the issue. I believe something must have changed in Vercel's infrastructure, because those calls were never cached before. 

I have prepared the pull request with `cache: no-store`, but I would like to learn a little more on how Vercel caches the response. 

According to https://vercel.com/docs/edge-network/caching, GET requests are cached based on `Cache-Control` header, which should work fine. 

In general, we **should** cache https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com response. The cache duration should be based on `Cache-Control` header returned by the endpoint. 

For me it seems that Vercel caches the response for too long, but I would have to experiment with this a bit to be sure.

I have some questions to you, which hopefully helps me to gather more insight on the issue:

How often does this error happen? Is it periodical per user, or affects all users at once? 

My understanding is that once `https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com` is cached, no one can login and `NO_MATCHING_KID` happens for every token validation. Is that the case?

**Comment by asaroukou** [comment]
Hi @awinogrodzk

Thank you for your response.
Hopefully we didn't experienced this issue on production.

Some of our engineers started seeing it on their deployment branches at different moments the last two weeks and we were able to check the keys of the cached response by Vercel against the newly updated keys from Google.

Also Since we are using `getTokens` to do some checks at functions level I can say that our issue is much more with the NodeJS engine and not the edge.

In preview the function using `getTokens` fail on token verification because it use the cache while on production the same function is actually doing the fetch. On the logs under `Request Metrics` Vercel will tell you what ressources your function tried to fetch and if it was resolved from the cache.
I also identified some endpoints on production using the cache with no issue and I assume that the cached data are somehow the right one.

**Comment by asaroukou** [comment]
About the implementation of the cache in the library, I found it weird that is was just a global Map instance. Can the life time of this instance exceed the function execution? I think in regular NodeJS backend with a server up 24h/7 it will work as long as you don't redeploy the backend. With Vercel I think you'll get a new and empty map on each function run.

**Comment by awinogrodzki** [comment]
In `keyResponseCache` we save both the keys and expiration date. Expiration date is based on `Cache-Control` header, and if it's exceeded, public keys are re-fetched: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/src/auth/signature-verifier.ts#L118 

This mechanism is basically the same as in official `firebase-admin` library.

> With Vercel I think you'll get a new and empty map on each function run.
Yes, you are correct. `keyResponseCache` is used only in Node.js runtime due to https://github.com/vercel/next.js/discussions/50577

**Comment by awinogrodzki** [comment]
To give you more context on https://github.com/vercel/next.js/discussions/50577 :

I was testing the library extensively against Vercel and Node.js runtimes back in the day and found out that Middleware is run in Edge Function, which does not expose any caching mechanism. 

This was really troublesome, because `https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com` response changes quite rarely (AFAIR ~15-30 days), so there is no point to fetch it on each request.

I started investigating `Next.js`'s overloaded `fetch` function from source code perspective and it was clear that `GET` requests made from Middleware to external URL's such as `https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com` were not cached at all. 

It seems Vercel has added some caching support, which is a good thing, but only if it respects `Cache-Control` header, which it claims to be doing

In general – `NO_MATCHING_KID` error is a result of Google's key rotation, and thus is expected. It should happen once in a while. 

What worries me is that you should never experience `NO_MATCHING_KID` error as a user of the library. In case `NO_MATCHING_KID` happens, it should be catched and re-thrown as `INVALID_ARGUMENT` with message as: `idToken has "kid" claim which does not correspond to a known public key. Most likely the token is expired, so get a fresh token from your client app and try again.` 

This is exactly how `firebase-admin` handles this scenario. It basically forces user to re-login after public keys have expired. 
 
 Here's a good explanation of this: https://stackoverflow.com/questions/70350163/firebase-expired-idtoken-becoming-invalid-after-1-week
 
> You can't. Key rotation is a critical security measure built into the service. In any case, the SDK catches these errors and converts them into InvalidIdTokenError. So you can just handle that to deal with this scenario.

**Comment by asaroukou** [comment]
We are actually getting the `INVALID_ARGUMENT` error and it's by checking in depth that we were able to trace the error to `NO_MATCHING_KID` and more specifically the Vercel cache issue.

Here is more insight in how the things works on our side.

We have the `middleware.ts` (edge runtime) containing all the logic for protecting pages from unauthenticated users. We are not protecting the `/api` path with the middleware.
On each `/api/someFunction/route.ts` (Node.js runtime) we have a custom logic using `getTokens` to extract custom claims from the cookies and it is at this step that the cookies verification is failing.

Login will work and you will be redirected to the protected page meaning the middleware has the rights and up to date certificates.
The protected page fails getting the data needed because the protected `api` serving them is unable to verify the cookies due to outdated cached certificates.
That's why logout + clearing client cookies AND THEN login doesn't solve the issue.

The `Cache-Control` on the response header from `Google` was about a day when I checked and is even less now but we were able to reproduced the issue on multiple deployments for more than a week. I will consider vercel has a real issue on this.

**Comment by awinogrodzki** [comment]
Thanks for the description!

I will reproduce this scenario in Vercel and analyze cookie behaviour. 

API routes run inside in Node.js runtime by default. Is this also your case? Do you export `runtime` variable in any `route.ts` file, as in https://nextjs.org/docs/app/building-your-application/routing/route-handlers#edge-and-nodejs-runtimes ?

Also, could you share your `config.matcher` value from `middleware.ts` file? I am interested in this part:

```tsx
export const config = {
  matcher: [
    '/',
    '/((?!_next|favicon.ico|api|.*\\.).*)',
    '/api/login',
    '/api/logout'
  ]
};
```

Feel free to remove any sensitive configuration – what I am interested in is if `matcher` allows to run middleware for `/api/someFunction/route.ts` routes. It will help me to narrow down possible sources of the issue.

**Comment by awinogrodzki** [comment]
I've released `next-firebase-auth-edge@1.4.1-debug.2` version which allows you to enable debug mode in `getTokens` and adds detailed logs about `fetchPublicTokens`

It should show logs similar to this:

```tsx
ⓘ next-firebase-auth-edge: Handle request
	 path: /
ⓘ next-firebase-auth-edge: Verifying user credentials...
ⓘ next-firebase-auth-edge: No public keys found in cache. Fetching public keys from Google...
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Public keys fetched
	 responseHeaders: {
  age: '52',
  alt-svc: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
  cache-control: 'public, max-age=18821, must-revalidate, no-transform',
  content-encoding: 'gzip',
  content-length: '1732',
  content-type: 'application/json; charset=UTF-8',
  date: 'Mon, 25 Mar 2024 22:18:24 GMT',
  expires: 'Tue, 26 Mar 2024 03:32:05 GMT',
  server: 'scaffolding on HTTPServer2',
  vary: 'Origin,X-Origin,Referer',
  x-content-type-options: 'nosniff',
  x-frame-options: 'SAMEORIGIN',
  x-xss-protection: '0'
}
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Public keys cached
	 cacheKey: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
	 expiresAt: 1711423976999
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Credentials verified successfully
ⓘ next-firebase-auth-edge: Successfully handled authenticated response
 ○ Compiling / ...
 ✓ Compiled / in 799ms (694 modules)
ⓘ next-firebase-auth-edge: Handle request
	 path: /
ⓘ next-firebase-auth-edge: Verifying user credentials...
ⓘ next-firebase-auth-edge: Get public keys from cache
	 expiresAt: 1711423976999
	 now: 1711405160210
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Credentials verified successfully
ⓘ next-firebase-auth-edge: Successfully handled authenticated response
ⓘ next-firebase-auth-edge: Handle request
	 path: /profile
ⓘ next-firebase-auth-edge: Verifying user credentials...
ⓘ next-firebase-auth-edge: Get public keys from cache
	 expiresAt: 1711423976999
	 now: 1711405161839
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Credentials verified successfully
ⓘ next-firebase-auth-edge: Successfully handled authenticated response
 ✓ Compiled /profile in 292ms (767 modules)
ⓘ next-firebase-auth-edge: Handle request
	 path: /profile
ⓘ next-firebase-auth-edge: Verifying user credentials...
ⓘ next-firebase-auth-edge: Get public keys from cache
	 expiresAt: 1711423976999
	 now: 1711405162205
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Credentials verified successfully
ⓘ next-firebase-auth-edge: Successfully handled authenticated response
 ✓ Compiled /api/user-counters in 85ms (485 modules)
ⓘ next-firebase-auth-edge: No public keys found in cache. Fetching public keys from Google...
	 cryptoRuntime: node:crypto
ⓘ next-firebase-auth-edge: Public keys fetched
	 responseHeaders: {
  age: '0',
  'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
  'cache-control': 'public, max-age=21019, must-revalidate, no-transform',
  'content-encoding': 'gzip',
  'content-length': '1732',
  'content-type': 'application/json; charset=UTF-8',
  date: 'Mon, 25 Mar 2024 22:19:24 GMT',
  expires: 'Tue, 26 Mar 2024 04:09:43 GMT',
  server: 'scaffolding on HTTPServer2',
  vary: 'Origin,X-Origin,Referer',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '0'
}
	 cryptoRuntime: node:crypto
ⓘ next-firebase-auth-edge: Public keys cached
	 cacheKey: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
	 expiresAt: 1711426183645
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: node:crypto
ⓘ next-firebase-auth-edge: Handle request
	 path: /profile
ⓘ next-firebase-auth-edge: Verifying user credentials...
ⓘ next-firebase-auth-edge: Get public keys from cache
	 expiresAt: 1711423976999
	 now: 1711405164906
	 digest: 7NpuQjnh3-6F8NV0UeO85J1c_8-NiEC72AYp1MbqUxM
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Credentials verified successfully
ⓘ next-firebase-auth-edge: Successfully handled authenticated response
```

The key fields to notice are `responseHeaders` which list headers returned from Google public keys endpoint, `digest` which is hash based on public keys, as well as `cryptoRuntime` which is a `jose` variable indicating Node.js or Edge runtime

I can observe following things:

* global `Map` cache seems to be functional both in `middleware.ts` (Edge runtime), as well as `route.ts` (Node.js runtime)
* Edge and Node.js runtime have separate instances of cache `Map`. This means that in theory, there can be discrepancy between the two. 
*  `GET https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com` returns random `Max-Age` value in `Cache-Control` header. Which increases the risk for Edge and Node.js cache to have different values
* Cache invalidation seems to be working correctly in both cases
* I cannot see Vercel caching the result of `fetch`. Neither on `Edge` nor in `Node.js` runtime.

My conclusion is as follows:

Most likely Edge and Node.js runtime have different cache expiry dates due to random `Max-Age` in `Cache-Control` header returned by Google.

Let's consider following scenario:

1. User logs in, a token is generated

2. User refreshes the page, calls `/api/someFunction/route`, all works as expected. Google public keys are cached by both middleware (Edge) and api route (Node.js), but with different expiry dates

3. Google rotates credentials

4. User refreshes the page, Middleware (Edge) cache expiry date is in future, page renders successfully

5. User calls `/api/someFunction/route`, Node.js cache expiry date is in the past, `NO_MATCHING_KID` error is thrown

What does not fit here is that: in mentioned scenario, calling `/api/login` should most definitely generate a token with fresh `kid` header, so repeated request to `/api/someFunction/route` should not fail with `NO_MATCHING_KID` error.

If you're experiencing repeated `NO_MATCHING_KID` error, the scenario must be somehow different in your case.

Are you able to reproduce the issue and share some `debug` logs?

**Comment by asaroukou** [comment]
We'll try to reproduce the issue. To move forward the last time we had the issue, we published a new version of our app (on the same vercel branch) with the workaround (`cache: "no-store"`). We just need it the issue to appear again.

I have an unrelated question about the peerDependency on `next: ^14.0.0`. Does it means that we can't/should not use the library with versions of next below v14.0.0 ?

**Comment by awinogrodzki** [comment]
As far as I remember, `next: ^14.0.0` peerDependency was set due to some type import path changes. Nothing that should cause a functional change.

Which Next.js version do you use? I can test the library with that version and maybe I can lower that restriction

**Comment by asaroukou** [comment]
Right now we are using `next 13.5.6`

**Comment by asaroukou** [comment]
> Also, could you share your `config.matcher` value from `middleware.ts` file? I am interested in this part:

this is our matcher
```typescript
const authConfig = {
  loginPath: "/api/auth/session",
  logoutPath: "/api/auth/logout",
  cookieName: "cookie-name",
  cookieSignatureKeys: ["secret1", "secret2"],
  ...
 }
 
export const config = {
  matcher: [
    "/api/auth/session",
    "/api/auth/logout",
    "/",
    "/((?!api|_next|favicon.ico|robots.txt|manifest.webmanifest|.*\\.).*)",
  ],
};
```

**Comment by asaroukou** [comment]
> * global `Map` cache seems to be functional both in `middleware.ts` (Edge runtime), as well as `route.ts` (Node.js runtime)

Just to be sure. Have you been able to confirm that it is working on vercel too. From my understanding the global Map will work with no issues on your machine since all the endpoints on your api (and probably the middleware) are juste standards nodejs handlers with no notion of warmup, cold start, etc. Since it is a long running server you probably won't lose the Map instance between two calls. On Vercel it is another story. I'm telling because your logs are from a development env 😄

**Comment by awinogrodzki** [comment]
> I'm telling because your logs are from a development env 😄

yes, I just copied console output as a quick example

I verified this in Vercel environment with multiple scenarios and I confirmed `Map` instance is shared between calls both in `Edge Function` (Edge runtime) and `Serverless Function` (Node.js runtime). I was surprised, but this seems to be the case. 

I will share some logs soon

**Comment by awinogrodzki** [comment]
Here's official [Firebase Custom ID token verification docs](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library) 

It is clearly describing the verification process:

> Finally, ensure that the ID token was signed by the private key corresponding to the token's kid claim. Grab the public key from https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com and use a JWT library to verify the signature.

> Use the value of max-age in the Cache-Control header of the response from that endpoint to know when to refresh the public keys.

We are doing exactly that. When `max-age` has been reached, we refresh public keys in each cache. On consecutive requests, Google public keys will be rotated – new keys will replace the others, one by one, until all initial keys have been replaced with new keys. When that happens, either Middleware or API Route, or both will fail with `INVALID_ARGUMENT`.

In that case you should re-authenticate with `/api/login` and all subsequent requests to Middleware or API Routes should be successfully authenticated

**Comment by asaroukou** [comment]
Hello @awinogrodzki 
Today we experienced the same issue again after one of the keys being rotated by Google.
The issue occurred on all of our environments including local dev server thus we can exclude the hypothesis of Vercel infrastructure being the root cause.

We were able to login properly and after investigation the had the right keys on the `middleware` and the wrong keys on the `nodejs functions`.
On vercel, `purging the cache` of the project fixed the issue and on local dev server removing the `.next` directory fixed the issue.

After a close look to the nextjs doc https://nextjs.org/docs/app/api-reference/functions/fetch#optionscache it seem's that all backend fetches are cached with this option by default `{cache: "force-cache"}`.

The previous proposed solution was passing `{cache: "no-store"}` but according to the doc https://developer.mozilla.org/en-US/docs/Web/API/Request/cache#value we wont cache anything anymore on this side. May be starting with `{cache: "default"}` as option will solve the issue and also prevent unnecessary request

**Comment by awinogrodzki** [comment]
Hey @asaroukou! Thanks for investigating! 

I say we can safely proceed with `cache: no-store` for fetching Google public certificates. We already have caching mechanism in place for this URL and the assumption was those requests are not cached at all (at least that's the behavior I see when testing with latest Next.js)

Today, I will release version `1.4.2` of `next-firebase-auth-edge` that will include updated `peerDependencies` to support your version of Next.js, as well as `cache: no-store` when fetching Google's public certificates.

**Comment by awinogrodzki** [comment]
I've released `next-firebase-auth-edge@1.4.2` with `cache: no-store`, updated `peerDependencies` and improved `debug` logs. Could you give it a try and let me know if that works?

**Comment by asaroukou** [comment]
Thanks 🙏. We are updating this dependency asap.

**Comment by asaroukou** [comment]
Hey @awinogrodzki! Thanks for your time. I tried the package on a local dev environment with the problem and it is working fine. We are now using the latest version of the package across the project 🙂. I guess this issue can be closed. Thanks again 😇.

**Comment by awinogrodzki** [comment]
Hello @asaroukou!

That's wonderful news! I will close the issue now. If anything comes up, don't hesitate to open another issue. 

Cheers 🎉
