### ISSUE TITLE
Dynamic Routes for publicPaths?

### ISSUE THREAD

**Issue by chrisvince** [awinogrodzki/next-firebase-auth-edge#168]
Love the package!

Wondering if it's possible to use dynamic routes for the `publicPaths` param for `redirectToLogin`?

For example:
```
handleInvalidToken: async () => {
  return redirectToLogin(request, {
    path: '/sign-in',
    publicPaths: [
      '/sign-in',
      '/sign-up',
      '/reset-password',
      '/post/:id', // <-- dynamic route
    ],
  })
},
```

This would allow the user access, for example, `/post/post-1` and `/post/post-2`.

**Comment by awinogrodzki** [comment]
Hey @chrisvince!

Thanks for the suggestion! 

I am going to introduce more advanced redirection functions to support this and other scenarios (like integration with next-intl mentioned in #169)

Keep in mind, that `redirectToLogin` is a helper function (very simple one), and it's completely fine to write your own implementations.

Here is a code for `redirectToLogin`:

```tsx
export function redirectToLogin(
  request: NextRequest,
  options: RedirectToLoginOptions = {
    path: '/login',
    publicPaths: ['/login']
  }
) {
  const redirectKey = options.redirectParamKeyName || 'redirect';

  if (options.publicPaths.includes(request.nextUrl.pathname)) {
    return NextResponse.next();
  }

  const url = request.nextUrl.clone();
  url.pathname = options.path;
  url.search = `${redirectKey}=${request.nextUrl.pathname}${url.search}`;
  return NextResponse.redirect(url);
}
```

As you see, it's pretty basic stuff!

**Comment by awinogrodzki** [comment]
Hey @chrisvince!

Thank you for your patience on this.

In [1.7.0-canary.17](https://github.com/awinogrodzki/next-firebase-auth-edge/compare/v1.7.0-canary.16...v1.7.0-canary.17), `redirectToLogin` function now accepts `RegExp` in addition to `string` in `publicPaths` option.

You can solve your problem by using this example:

```tsx
handleInvalidToken: async () => {
  return redirectToLogin(request, {
    path: '/sign-in',
    publicPaths: [
      '/sign-in',
      '/sign-up',
      '/reset-password',
      /^\/post\/(\w+)/
    ],
  })
},
```

I decided to use `RegExp` instead of path pattern strings for versatility and simplicity. 

Let me know how it works for you!
