### ISSUE TITLE
middleware requests fail when API Keys have restricted domain access

### ISSUE THREAD

**Issue by jdgazlay** [awinogrodzki/next-firebase-auth-edge#171]
If you set a domain restriction on your api key credential in Google Cloud APIs & Services the middleware requests will fail. Error logs show the referrer is `<empty>`.

**Comment by awinogrodzki** [comment]
Hey @jdgazlay! 

Thanks for reporting. I will test this scenario soon and get back to you 🦾

**Comment by awinogrodzki** [comment]
Hey @jdgazlay! 

Thanks for your patience. I've released v1.5 canary (`next-firebase-auth-edge@v1.5.0-canary.1`) with domain-restricted Firebase API Keys support. 

In order to pass referer information to Google APIs when extracting tokens, you need to pass new `headers` option when calling `getTokens`. 

You can follow [v1.5.x canary release](https://github.com/awinogrodzki/next-firebase-auth-edge/pull/186) and [Firebase API key domain restriction](https://next-firebase-auth-edge-docs.vercel.app/docs/usage/domain-restriction) docs for more details

**Comment by jdgazlay** [comment]
Hey @awinogrodzki, I'll give this update a try soon and let you know how it works. Thank you! 🙏

**Comment by awinogrodzki** [comment]
I will close the issue now, as `1.5` is officially released and I've tested domain restriction on api keys in several test projects. Feel free to reopen the issue if you still face some problems with this
