### ISSUE TITLE
support for setCustomUserClaims?

### ISSUE THREAD

**Issue by GorvGoyl** [awinogrodzki/next-firebase-auth-edge#32]
Is it possible to set custom user claims (https://firebase.google.com/docs/auth/admin/custom-claims) using this library in vercel edge functions?

**Comment by awinogrodzki** [comment]
Hey @GorvGoyl! Thanks for the question.

Currently the library does not support `setCustomUserClaims`, but I plan to implement this.

What I currently use to set custom claims is Next.js API Handler (which is run on Node.js instead of Edge by default) and official firebase-admin library. After updating custom claims I run `refreshAuthCookies` to update user tokens: https://github.com/awinogrodzki/next-firebase-auth-edge#refreshauthcookies

Could you describe your use case? How would you use `setCustomUserClaims`? I will mark this issue as a feature request, so you can track the progress

**Comment by GorvGoyl** [comment]
I use custom claims to store user data and not relying upon any additional database. I update these claims whenever paid user makes some api call like updating the credits usage etc.

**Comment by GorvGoyl** [comment]
this should be resourceful https://github.com/firebase/firebase-admin-node/issues/2122#issuecomment-1481408517

**Comment by awinogrodzki** [comment]
Hey @GorvGoyl!
