### ISSUE TITLE
Failed to compile error

### ISSUE THREAD

**Issue by rgbskills** [awinogrodzki/next-firebase-auth-edge#52]
Hello I'm using NextJS 13.4.4 and I simply copied over the files from "next13-typescript-static-pages" and I am getting the following error:

```js
./node_modules/next-firebase-auth-edge/lib/next/middleware.js
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| Object.defineProperty(exports, "__esModule", {
```

**Comment by awinogrodzki** [comment]
Hey @rgbskills, 

Thanks for reporting.

I was able to reproduce the error. It's a fault of Next.js SWC compiler rendering multiple variable declarations. The fix is coming in https://github.com/vercel/next.js/pull/50376

To fix the issue you can either downgrade `next` to `13.4.1` or upgrade to `13.4.5-canary.0`

Cheers!
