### ISSUE TITLE
Invalid credentials error when navigating quickly between pages

### ISSUE THREAD

**Issue by Kaeldehta** [awinogrodzki/next-firebase-auth-edge#99]
I am currently implementing the navigation part of a website and while navigating between pages I sometimes get this error:

` Error: Invalid credentials: Error fetching access token: {"code":400,"message":"QUOTA_EXCEEDED","status":"INVALID_ARGUMENT"} 
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:66:14)
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:103:25)
    at (node_modules/next-firebase-auth-edge/lib/next/middleware.js:56:40)
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:87:27)
    at (middleware.ts:51:34)
    at (node_modules/next/dist/esm/server/web/adapter.js:150:19) {
  code: 'INVALID_CREDENTIAL'
}`

I guess there is some firebase quota that is exceeded but I can't seem to pinpoint what is happening there.
When this error occurs I redirect back to the login page, but the user is still logged in (I can just refresh the page to verify it)

I am using next 13.5.3 and next-firebase-auth-edge version 0.8.6

Maybe you have an idea what's going on.
Thanks a lot

**Comment by awinogrodzki** [comment]
Hey @Kaeldehta! Thanks for reporting the issue!

The error happens due to too many calls to `https://securetoken.googleapis.com/v1/token?key=API_KEY&grant_type=refresh_token&refresh_token=REFRESH_TOKEN`.

Token refresh should not happen more than once in 1 hour. 

How often does this error happen?

Is it periodical? Does the app start working normally after a refresh?

There might be couple of reasons for this happening:

1. Once in 1 hour, when user token becomes invalid, there might be multiple concurrent requests to authenticated routes happening, each call is made with expired token, so each request is causing a token refresh of its own

2. User comes back to the app after ~1 hour and starts making authenticated calls without navigating the page 

3. There is some time discrepancy between instances of the server, causing token to be always expired


If I had to guess, I would say it's 1. 

Next.js does automatically preload pages from links visible on the website, which can cause a number of concurrent request with expired cookies. 

Could you run `npx next info` in the affected environment and paste it here?

Also, do you run into this error locally, external Node.js environment or Vercel environment?

**Comment by Kaeldehta** [comment]
Hey @awinogrodzki,

thank you for the detailed answer.

What you described makes total sense to me, the question is what to do when it actually is the first case,
I could in theory just filter out this error, but this would mean that these pages where the error happened would then end up with missing user credentials since the middleware didn't set the session cookies.

I saw this error happening on Vercel. I have to find out how to be able to run next info inside of the Vercel environment.

**Comment by Kaeldehta** [comment]
Hey @awinogrodzki,
I just installed the mentioned version, included the verification token caching in the middleware and tried it out again.
Still happens. But I did verify now that it happens whenever the token expires.
Also tried it out locally using the build generated by npm run build and the same thing happens.

What I saw during testing is that the idToken in the AuthCookie never is really refreshed as far as I can see.
Should the exp claim not be different when the token is refreshed?
Maybe I am misunderstanding something.

I try to setup a repo with reproducible code, this will probably take a bit since I have to setup a firebase project as well.

**Comment by awinogrodzki** [comment]
@Kaeldehta, 

> Should the exp claim not be different when the token is refreshed?
Yes, it should. Every 1 hour, a request to Next.js server should return `Set-Cookie` headers with new tokens.

Which means, that every hour token and signature cookies should update. I would start by inspecting why those cookies are not being updated.

You can notice it in Dev Tools, when refreshing a page after token have expired:
[Screen Recording 2023-10-12 at 11.56.50.webm](https://github.com/awinogrodzki/next-firebase-auth-edge/assets/12574743/7cd2d88a-f790-4990-9dbe-ee520450178d)

**Comment by Kaeldehta** [comment]
Found the problem. I am using another middleware and was combining the two responses incorrectly. 
This meant the cookie was never updated after the token expired.
Hopefully this also fixes the quota problem, since the cookie is now updated correctly.

Thank you again for your help! And thanks for this great library :)
